packages:
  - .

overrides:
  '@babel/runtime': ^7.26.10
  brace-expansion: ^2.0.3
  diff: ^4.0.4
  effect: ^3.20.0
  glob: ^10.5.0
  minimatch: ^9.0.7
  picomatch: ^2.3.2
  postcss: ^8.5.10
  uuid: ^11.1.1
  yaml: ^2.8.3

allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  sharp: false
